// <auto-generated />
namespace PizzaWebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedcurrentVouchertoorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcurrentVouchertoorder));
        
        string IMigrationMetadata.Id
        {
            get { return "201701221744213_added-currentVoucher-to-order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
